export const posts = [
  {
    id: 1,
    url: "../Asset/0ca3ac3d979e4c22ef2efb16a6b3e0b0.png",
    name: "Olivia Rhye",
    username: "@amuluonyenego",
    time: "1hr",
    projectName:
      "Design and construction of control panel for marine diesel engine",
    text: "I am looking for who to help me work on my final year project, the topic is design and construction of control panel for marine diesel engine",
    profession: ["mechanical Engineering","marine Engineering"],
    amt: "10,000",
  },
  {
    id: 2,
    url: "../Asset/0ca3ac3d979e4c22ef2efb16a6b3e0b0.png",
    name: "Olivia Rhye",
    username: "@amuluonyenego",
    time: "5hrs",
    projectName:
      "Design and construction of control panel for marine diesel engine",
    text: "I am looking for who to help me work on my final year project, the topic is design and construction of control panel for marine diesel engine",
    profession: ["mechanical Engineering","marine Engineering"],
    amt: "10,000",
  },
  {
    id: 3,
    url: "../Asset/0ca3ac3d979e4c22ef2efb16a6b3e0b0.png",
    name: "Olivia Rhye",
    username: "@amuluonyenego",
    time: "2 days",
    projectName:
      "Design and construction of control panel for marine diesel engine",
    text: "I am looking for who to help me work on my final year project, the topic is design and construction of control panel for marine diesel engine",
    profession: ["mechanical Engineering","marine Engineering"],
    amt: "10,000",
  },
  {
    id: 4,
    url: "../Asset/0ca3ac3d979e4c22ef2efb16a6b3e0b0.png",
    name: "Olivia Rhye",
    username: "@amuluonyenego",
    time: "2 days",
    projectName:
      "Design and construction of control panel for marine diesel engine",
    text: "I am looking for who to help me work on my final year project, the topic is design and construction of control panel for marine diesel engine",
    profession: ["mechanical Engineering","marine Engineering"],
    amt: "10,000",
  },
  {
    id: 5,
    url: "../Asset/0ca3ac3d979e4c22ef2efb16a6b3e0b0.png",
    name: "Olivia Rhye",
    username: "@amuluonyenego",
    time: "2 days",
    projectName:
      "Design and construction of control panel for marine diesel engine",
    text: "I am looking for who to help me work on my final year project, the topic is design and construction of control panel for marine diesel engine",
    profession: ["mechanical Engineering","marine Engineering"],
    amt: "10,000",
  },
  {
    id: 6,
    url: "../Asset/0ca3ac3d979e4c22ef2efb16a6b3e0b0.png",
    name: "Olivia Rhye",
    username: "@amuluonyenego",
    time: "2 days",
    projectName:
      "Design and construction of control panel for marine diesel engine",
    text: "I am looking for who to help me work on my final year project, the topic is design and construction of control panel for marine diesel engine",
    profession: ["mechanical Engineering","marine Engineering"],
    amt: "10,000",
  },
  {
    id: 7,
    url: "../Asset/0ca3ac3d979e4c22ef2efb16a6b3e0b0.png",
    name: "Olivia Rhye",
    username: "@amuluonyenego",
    time: "2 days",
    projectName:
      "Design and construction of control panel for marine diesel engine",
    text: "I am looking for who to help me work on my final year project, the topic is design and construction of control panel for marine diesel engine",
    profession: ["mechanical Engineering","marine Engineering"],
    amt: "10,000",
  },
  {
    id: 8,
    url: "../Asset/0ca3ac3d979e4c22ef2efb16a6b3e0b0.png",
    name: "Olivia Rhye",
    username: "@amuluonyenego",
    time: "2 days",
    projectName:
      "Design and construction of control panel for marine diesel engine",
    text: "I am looking for who to help me work on my final year project, the topic is design and construction of control panel for marine diesel engine",
    profession: ["mechanical Engineering","marine Engineering"],
    amt: "10,000",
  },
  {
    id: 9,
    url: "../Asset/0ca3ac3d979e4c22ef2efb16a6b3e0b0.png",
    name: "Olivia Rhye",
    username: "@amuluonyenego",
    time: "2 days",
    projectName:
      "Design and construction of control panel for marine diesel engine",
    text: "I am looking for who to help me work on my final year project, the topic is design and construction of control panel for marine diesel engine",
    profession: ["mechanical Engineering","marine Engineering"],
    amt: "10,000",
  },
  {
    id: 10,
    url: "../Asset/0ca3ac3d979e4c22ef2efb16a6b3e0b0.png",
    name: "Olivia Rhye",
    username: "@amuluonyenego",
    time: "2 days",
    projectName:
      "Design and construction of control panel for marine diesel engine",
    text: "I am looking for who to help me work on my final year project, the topic is design and construction of control panel for marine diesel engine",
    profession: ["mechanical Engineering","marine Engineering"],
    amt: "10,000",
  },
  {
    id: 11,
    url: "../Asset/0ca3ac3d979e4c22ef2efb16a6b3e0b0.png",
    name: "Olivia Rhye",
    username: "@amuluonyenego",
    time: "2 days",
    projectName:
      "Design and construction of control panel for marine diesel engine",
    text: "I am looking for who to help me work on my final year project, the topic is design and construction of control panel for marine diesel engine",
    profession: ["mechanical Engineering","marine Engineering"],
    amt: "10,000",
  },
];
